[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=allure-results
markers =
    constructor: тесты конструктора
    feed: тесты ленты заказов